spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: 4119041190a
  #flyway:
    #baselineOnMigrate: true
server:
  port: 8081
  servlet:
    context-path: /chat
